# Configuration de la protection des branches
branches:
  main:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - quality / Code Style Check
          - quality / SonarQube Analysis
          - unit-tests / Run Unit Tests
          - integration-tests / Run API Integration Tests
          - security / OWASP Dependency Check
          - build / Build with Maven
          - deploy-staging / Deploy to Staging
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []

  develop:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - quality / Code Style Check
          - unit-tests / Run Unit Tests
          - build / Build with Maven
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: false
