name: Data Management

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: myprof_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Validate Database Migrations
        run: |
          ./mvnw flyway:validate
          
      - name: Test Database Rollback
        run: |
          ./mvnw flyway:migrate flyway:undo
          
      - name: Check Database Indexes
        run: |
          ./mvnw test -Dtest=*DatabaseIndexTest
          
      - name: Verify Data Consistency
        run: |
          ./mvnw test -Dtest=*DataConsistencyTest
          
  caching:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Implementation Tests
        run: |
          ./mvnw test -Dtest=*CacheTest
          
      - name: Cache Eviction Tests
        run: |
          ./mvnw test -Dtest=*CacheEvictionTest
          
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Verify Backup Procedures
        run: |
          ./mvnw test -Dtest=*BackupTest
          
      - name: Test Data Recovery
        run: |
          ./mvnw test -Dtest=*RecoveryTest
