name: Monolith Monitoring

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Verify Spring Actuator
        run: |
          ./mvnw spring-boot:run &
          sleep 30
          curl -f http://localhost:8080/actuator/health
          curl -f http://localhost:8080/actuator/metrics
          
      - name: Check Logging Configuration
        run: |
          if ! grep -r "logback-spring.xml" src/main/resources; then
            echo "Missing logging configuration"
            exit 1
          fi
          
      - name: Validate Application Metrics
        run: |
          ./mvnw test -Dtest=*MetricsTest
          
      - name: Check Memory Usage
        run: |
          ./mvnw test -Dtest=*MemoryTest
