name: Database Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: myprof_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Check Database Migrations
        run: |
          ./mvnw flyway:validate
          
      - name: Verify Database Connections
        run: |
          ./mvnw test -Dtest=*DatabaseConnectionTest
          
      - name: Test Connection Pool
        run: |
          ./mvnw test -Dtest=*ConnectionPoolTest
          
      - name: Check Query Performance
        run: |
          ./mvnw test -Dtest=*QueryPerformanceTest
