name: Monolith Security

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Check Spring Security Config
        run: |
          if ! grep -r "SecurityConfiguration" src/main/java; then
            echo "Missing Spring Security configuration"
            exit 1
          fi
          
      - name: OWASP Dependency Check
        run: |
          ./mvnw org.owasp:dependency-check-maven:check
          
      - name: Test Authentication
        run: |
          ./mvnw test -Dtest=*AuthenticationTest
          
      - name: Test Authorization
        run: |
          ./mvnw test -Dtest=*AuthorizationTest
          
      - name: Check SSL Configuration
        run: |
          ./mvnw test -Dtest=*SSLTest
          
      - name: Validate Session Management
        run: |
          ./mvnw test -Dtest=*SessionManagementTest
