name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        
      - name: Build Docker image
        run: docker build -t myprof-backend .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker image
        run: |
          docker tag myprof-backend ${{ secrets.DOCKERHUB_USERNAME }}/myprof-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myprof-backend:latest
          
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Staging
        uses: actions/deploy-pages@v2
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
