name: Create Issue from Branch

on:
  create:
    branches:
      - '*'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.ref;
            const branchPattern = /^(feature|bugfix|hotfix|release)\/MYPROF-(\d+)-(.+)$/;
            const match = branchName.match(branchPattern);
            
            if (!match) {
              console.log(`❌ Format de branche invalide: ${branchName}`);
              console.log('Format attendu: type/MYPROF-XXX-description');
              console.log('Types valides: feature, bugfix, hotfix, release');
              return;
            }
            
            const [, type, issueNumber, description] = match;
            
            // Conversion en titre lisible
            const title = description
              .split('-')
              .map(word => word.charAt(0).toUpperCase() + word.slice(1))
              .join(' ');
            
            // Template d'issue selon le type
            const templates = {
              feature: `
                ## 🚀 Nouvelle Fonctionnalité
                
                ### Description
                Implémentation de : ${title}
                
                ### Objectifs
                - [ ] Analyse des besoins
                - [ ] Design technique
                - [ ] Implémentation
                - [ ] Tests unitaires
                - [ ] Tests d'intégration
                - [ ] Documentation
                
                ### Critères d'Acceptation
                - [ ] La fonctionnalité répond aux besoins spécifiés
                - [ ] Les tests passent à 100%
                - [ ] La documentation est à jour
                - [ ] Le code est revu et approuvé
                
                ### Informations Techniques
                - **Branch:** ${branchName}
                - **Jira:** [MYPROF-${issueNumber}](https://myprof.atlassian.net/browse/MYPROF-${issueNumber})
                - **Type:** Feature
              `,
              
              bugfix: `
                ## 🐛 Correction de Bug
                
                ### Description
                Correction de : ${title}
                
                ### Actions
                - [ ] Reproduction du bug
                - [ ] Analyse de la cause
                - [ ] Implémentation du fix
                - [ ] Tests de régression
                - [ ] Validation en staging
                
                ### Validation
                - [ ] Le bug est corrigé
                - [ ] Pas d'effets secondaires
                - [ ] Tests ajoutés pour éviter la régression
                
                ### Informations Techniques
                - **Branch:** ${branchName}
                - **Jira:** [MYPROF-${issueNumber}](https://myprof.atlassian.net/browse/MYPROF-${issueNumber})
                - **Type:** Bugfix
              `,
              
              hotfix: `
                ## 🚨 Hotfix Production
                
                ### Description
                Correction urgente : ${title}
                
                ### Actions Immédiates
                - [ ] Analyse d'impact
                - [ ] Correction
                - [ ] Tests critiques
                - [ ] Déploiement en production
                
                ### Post-Mortem
                - [ ] Analyse de la cause racine
                - [ ] Documentation de l'incident
                - [ ] Mesures préventives
                
                ### Informations Techniques
                - **Branch:** ${branchName}
                - **Jira:** [MYPROF-${issueNumber}](https://myprof.atlassian.net/browse/MYPROF-${issueNumber})
                - **Type:** Hotfix 🚨
              `,
              
              release: `
                ## 📦 Release
                
                ### Version
                ${title}
                
                ### Checklist
                - [ ] Merge des features
                - [ ] Tests de régression
                - [ ] Migration base de données
                - [ ] Documentation mise à jour
                - [ ] Release notes
                
                ### Validation
                - [ ] Tests staging OK
                - [ ] Performance validée
                - [ ] Sécurité vérifiée
                
                ### Informations Techniques
                - **Branch:** ${branchName}
                - **Jira:** [MYPROF-${issueNumber}](https://myprof.atlassian.net/browse/MYPROF-${issueNumber})
                - **Type:** Release
              `
            };
            
            // Labels selon le type
            const labels = {
              feature: ['enhancement', '👨‍💻 feature'],
              bugfix: ['bug', '🐛 fix'],
              hotfix: ['bug', 'urgent', '🚨 hotfix'],
              release: ['release', '📦 deploy']
            };
            
            try {
              // Création de l'issue
              const issue = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[${type.toUpperCase()}] ${title}`,
                body: templates[type],
                labels: labels[type],
                assignee: context.actor
              });
              
              console.log(`✅ Issue créée: ${issue.data.html_url}`);
              
              // Commentaire avec lien vers la branche
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.data.number,
                body: `Branch créée: [${branchName}](${context.payload.repository.html_url}/tree/${branchName})`
              });
              
            } catch (error) {
              console.error('❌ Erreur:', error);
              throw error;
            }
