spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: myprof_staging
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    com.myprof: INFO
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

# Configuration spécifique au staging
app:
  security:
    jwt:
      expiration: 3600000  # 1 heure
  cors:
    allowed-origins: https://staging.myprof.com
  feature-flags:
    enable-swagger: true
    enable-dev-tools: false
