name: Quality Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
          
      - name: Code Style Check
        run: |
          ./mvnw checkstyle:check
          ./mvnw spotless:check
          
      - name: PMD Analysis
        run: ./mvnw pmd:check
        
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=myprof-backend \
            -Dsonar.organization=mfradj \
            -Dsonar.host.url=https://sonarcloud.io
            
      - name: Check Code Format
        run: ./mvnw spring-javaformat:check
        
      - name: Upload Quality Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: quality-report
          path: target/site/
