name: Compliance & GDPR

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check GDPR Compliance
        run: |
          # Vérifier la présence des endpoints obligatoires GDPR
          ./mvnw test -Dtest=*GDPRTest
          
      - name: Verify Data Encryption
        run: |
          # Vérifier que les données sensibles sont chiffrées
          if ! grep -r "encryption" src/main/resources; then
            echo "Missing encryption configuration"
            exit 1
          fi
          
      - name: Check Audit Logging
        run: |
          # Vérifier la présence des logs d'audit
          if ! grep -r "AuditEventRepository" src/main/java; then
            echo "Missing audit logging"
            exit 1
          fi
          
      - name: Validate Data Retention
        run: |
          # Vérifier les politiques de rétention des données
          ./mvnw test -Dtest=*DataRetentionTest
          
      - name: Check Privacy Policy
        run: |
          if [ ! -f "src/main/resources/privacy-policy.md" ]; then
            echo "Missing privacy policy document"
            exit 1
          fi
          
      - name: Verify Consent Management
        run: |
          ./mvnw test -Dtest=*ConsentManagementTest
          
  data-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Data Access Controls
        run: |
          ./mvnw test -Dtest=*DataAccessTest
          
      - name: Verify Right to be Forgotten
        run: |
          ./mvnw test -Dtest=*DataDeletionTest
          
      - name: Check Data Portability
        run: |
          ./mvnw test -Dtest=*DataExportTest
