name: Monolith Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Application
        run: |
          ./mvnw clean package -DskipTests
          
      - name: Run Application Tests
        run: |
          ./mvnw test
          
      - name: Build Docker Image
        run: |
          docker build -t myprof-backend:latest .
          
      - name: Check Application Startup
        run: |
          docker run -d -p 8080:8080 myprof-backend:latest
          sleep 30
          curl -f http://localhost:8080/actuator/health
          
      - name: Check Memory Requirements
        run: |
          docker stats --no-stream myprof-backend
          
  backup:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Database Backup Check
        run: |
          ./mvnw test -Dtest=*BackupTest
          
      - name: Verify Backup Integrity
        run: |
          ./mvnw test -Dtest=*BackupIntegrityTest
