name: Environment Deployment

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches: [ main, develop ]
    
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: development
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
          
      - name: Build for Dev
        run: |
          ./mvnw clean package -P dev -DskipTests
          
      - name: Deploy to Dev
        env:
          SPRING_PROFILES_ACTIVE: dev
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Deploying to Development Environment"
          # Commandes de déploiement pour dev

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: staging
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
          
      - name: Build for Staging
        run: |
          ./mvnw clean package -P staging -DskipTests
          
      - name: Run Integration Tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_STAGING_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          ./mvnw verify -P staging
          
      - name: Deploy to Staging
        env:
          SPRING_PROFILES_ACTIVE: staging
          MONGODB_URI: ${{ secrets.MONGODB_STAGING_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Deploying to Staging Environment"
          # Commandes de déploiement pour staging

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
          
      - name: Build for Production
        run: |
          ./mvnw clean package -P prod -DskipTests
          
      - name: Security Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw verify sonar:sonar -P prod
          
      - name: Deploy to Production
        env:
          SPRING_PROFILES_ACTIVE: prod
          MONGODB_URI: ${{ secrets.MONGODB_PROD_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          echo "Deploying to Production Environment"
          # Commandes de déploiement pour production
