name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Run Unit Tests
        run: ./mvnw test -Dtest="**/*Tes!t.java"
        
      - name: Run Service Tests
        run: ./mvnw test -Dtest="**/*ServiceTest.java"
        
      - name: Run Controller Tests
        run: ./mvnw test -Dtest="**/*ControllerTest.java"
        
      - name: Generate Test Reports
        if: always()
        run: ./mvnw surefire-report:report-only
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: target/site/surefire-report.html
