name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: myprof_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Run API Integration Tests
        run: ./mvnw test -Dtest="**/*IT.java"
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/myprof_test
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          
      - name: Run Database Integration Tests
        run: ./mvnw test -Dtest="**/*RepositoryTest.java"
        
      - name: Generate Integration Test Report
        if: always()
        run: ./mvnw failsafe:integration-test failsafe:verify
        
      - name: Upload Integration Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: target/failsafe-reports/
