name: Performance Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run JMeter Performance Tests
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: performance-tests/load-test.jmx
          outputReportsFolder: performance-reports/
          
      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: performance-tests/k6-test.js
          
      - name: Upload Performance Results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance-reports/
