name: Performance Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build Application
        run: ./mvnw clean package -DskipTests
        
      - name: Start Spring Boot Application
        run: java -jar target/*.jar &
        
      - name: Wait for Application
        run: |
          while ! nc -z localhost 8080; do
            sleep 1
          done
          
      - name: Run JMeter Load Tests
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: src/test/jmeter/load-test.jmx
          outputReportsFolder: jmeter-reports/
          
      - name: Run Gatling Stress Tests
        run: ./mvnw gatling:test
        
      - name: API Response Time Tests
        run: ./mvnw verify -Pperformance
        
      - name: Upload Performance Results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: |
            jmeter-reports/
            target/gatling/
            target/performance-reports/
