name: End-to-End Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: myprof_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
          
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build and Start Application
        run: |
          ./mvnw clean package -DskipTests
          java -jar target/*.jar &
          
      - name: Run Cucumber E2E Tests
        run: ./mvnw verify -Pcucumber
        
      - name: Run Selenium Tests
        run: ./mvnw verify -Pselenium
        
      - name: Run Business Flow Tests
        run: ./mvnw verify -Pbusiness-flows
        
      - name: Generate E2E Report
        if: always()
        run: ./mvnw serenity:aggregate
        
      - name: Upload E2E Results
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-results
          path: target/site/serenity/
