name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
        
      - name: Build Docker Image
        run: |
          docker build -t myprof-backend:${{ github.sha }} .
          docker tag myprof-backend:${{ github.sha }} myprof-backend:latest
          
      - name: Run Trivy Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myprof-backend:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker Image
        run: |
          docker push myprof-backend:${{ github.sha }}
          docker push myprof-backend:latest
          
  deploy-staging:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        uses: actions/deploy-pages@v2
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          
      - name: Verify Deployment
        run: |
          curl --retry 10 --retry-delay 30 -f https://staging.myprof.com/actuator/health
