name: Code Style Check

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/**'

jobs:
  code-style:
    name: Code Style Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Check Code Style
        run: mvn checkstyle:check
        
      - name: Upload Style Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-results
          path: target/checkstyle-result.xml
