name: Code Coverage

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/**'

jobs:
  coverage:
    name: Code Coverage Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Generate Coverage Report
        run: |
          mvn jacoco:prepare-agent test jacoco:report
          mvn jacoco:check -Djacoco.minimum.coverage=0.70
          
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco/
