name: Feature Branch Tests

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest pytest-cov pytest-mongodb
          
      - name: Run linting
        run: |
          pylint $(git ls-files '*.py')
          
      - name: Run unit tests
        env:
          MONGODB_URI: mongodb://localhost:27017/test_db
        run: |
          pytest tests/unit --cov=./src --cov-report=xml
          
      - name: Check dependencies
        run: |
          pip check
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
