name: Integration Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/**'

jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Run Integration Tests
        run: |
          # Vérifier si des tests d'intégration existent
          if find src/test/java -name "*IT.java" -o -name "*IntegrationTest.java" | grep -q .; then
            mvn verify -Dtest=none -DfailIfNoTests=false -DskipUnitTests=true -Dintegration-tests=true
          else
            echo "Aucun test d'intégration trouvé - étape marquée comme réussie"
            exit 0
          fi
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/test_db
          
      - name: Upload Integration Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: target/failsafe-reports/
