name: Security Analysis

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/**'

jobs:
  security:
    name: Security Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Security Check
        run: mvn dependency-check:check -DfailBuildOnCVSS=7
        
      - name: Upload Security Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: target/dependency-check-report.html
