name: Unit Tests & Compilation

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - 'feature/**'

jobs:
  unit-tests:
    name: Compile & Unit Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Compile
        run: mvn clean compile
        
      - name: Run Unit Tests
        run: mvn test
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/test_db
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: target/surefire-reports/
